// 
// This source code was auto-generated by xsd, Version=2.0.50727.42. and then modified a lot
// 
namespace Jstor.JstorService {
    using System.Xml.Serialization;

    public interface IHasValue { string Value { get; set; } }
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.loc.gov/zing/srw/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.loc.gov/zing/srw/", IsNullable=false)]
    public class searchRetrieveResponse {
        
        /// <remarks/>
        public virtual string version { get; set; }
        
        /// <remarks/>
        public virtual string numberOfRecords { get; set; }
        
        /// <remarks/>
        public virtual string nextRecordPosition { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("record", typeof(searchRetrieveResponseRecordsRecord), IsNullable=false)]
        public virtual searchRetrieveResponseRecordsRecord[] records { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("echoedSearchRetrieveRequest")]
        public virtual searchRetrieveResponseEchoedSearchRetrieveRequest[] echoedSearchRetrieveRequest { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.loc.gov/zing/srw/")]
    public class searchRetrieveResponseRecordsRecord
    {

        /// <remarks/>
        public virtual string recordSchema { get; set; }
        
        /// <remarks/>
        public virtual string recordPacking { get; set; }
        
        /// <remarks/>
        public virtual string recordPosition { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recordData")]
        public virtual searchRetrieveResponseRecordsRecordRecordData[] recordData { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.loc.gov/zing/srw/")]
    public class searchRetrieveResponseRecordsRecordRecordData
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/")]
        public virtual string relation { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/")]
        public virtual string language { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/")]
        public virtual string coverage { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/")]
        public virtual string publisher { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/")]
        public virtual string title { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/")]
        public virtual string description { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=true)]
        public virtual creator[] creator { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=true)]
        public virtual identifier[] identifier { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=true)]
        public virtual type[] type { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=true)]
        public virtual date[] date { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=true)]
        public virtual subject[] subject { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="info:srw/schema/1/dc-v1.1")]
    //[System.Xml.Serialization.XmlRootAttribute(Namespace="info:srw/schema/1/dc-v1.1", IsNullable=false)]
    public class dc {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/")]
        public virtual string relation { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/")]
        public virtual string language { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/")]
        public virtual string coverage { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/")]
        public virtual string publisher { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/")]
        public virtual string title { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/")]
        public virtual string description { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=true)]
        public virtual creator[] creator { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=true)]
        public virtual identifier[] identifier { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=true)]
        public virtual type[] type { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=true)]
        public virtual date[] date { get; set; }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=true)]
        public virtual subject[] subject { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=true)]
    public class creator : IHasValue
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public virtual string Value { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=true)]
    public class identifier : IHasValue
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public virtual string Value { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=true)]
    public class type : IHasValue
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public virtual string Value {get; set;}
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=true)]
    public class date : IHasValue
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public virtual string Value {get; set;}
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://purl.org/dc/elements/1.1/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://purl.org/dc/elements/1.1/", IsNullable=true)]
    public class subject : IHasValue
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public virtual string Value { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.loc.gov/zing/srw/")]
    public class searchRetrieveResponseEchoedSearchRetrieveRequest
    {
        /// <remarks/>
        public virtual string version { get; set; }
        
        /// <remarks/>
        public virtual string query { get; set; }
        
        /// <remarks/>
        public virtual string startRecord { get; set; }
        
        /// <remarks/>
        public virtual string maximumRecords { get; set; }
        
        /// <remarks/>
        public virtual string recordPacking { get; set; }
        
        /// <remarks/>
        public virtual string recordSchema { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.loc.gov/zing/srw/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.loc.gov/zing/srw/", IsNullable=false)]
    public class NewDataSet
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("srw:searchRetrieveResponse")]
        public virtual searchRetrieveResponse[] Items { get; set; }
    }
}
