//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCalais.Calais {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://clearforest.com/", ConfigurationName="Calais.calaisSoap")]
    public interface calaisSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clearforest.com/Enlighten", ReplyAction="*")]
        OpenCalais.Calais.EnlightenResponse Enlighten(OpenCalais.Calais.EnlightenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://clearforest.com/Enlighten", ReplyAction="*")]
        System.IAsyncResult BeginEnlighten(OpenCalais.Calais.EnlightenRequest request, System.AsyncCallback callback, object asyncState);
        
        OpenCalais.Calais.EnlightenResponse EndEnlighten(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnlightenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Enlighten", Namespace="http://clearforest.com/", Order=0)]
        public OpenCalais.Calais.EnlightenRequestBody Body;
        
        public EnlightenRequest() {
        }
        
        public EnlightenRequest(OpenCalais.Calais.EnlightenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://clearforest.com/")]
    public partial class EnlightenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string licenseID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string paramsXML;
        
        public EnlightenRequestBody() {
        }
        
        public EnlightenRequestBody(string licenseID, string content, string paramsXML) {
            this.licenseID = licenseID;
            this.content = content;
            this.paramsXML = paramsXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnlightenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnlightenResponse", Namespace="http://clearforest.com/", Order=0)]
        public OpenCalais.Calais.EnlightenResponseBody Body;
        
        public EnlightenResponse() {
        }
        
        public EnlightenResponse(OpenCalais.Calais.EnlightenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://clearforest.com/")]
    public partial class EnlightenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnlightenResult;
        
        public EnlightenResponseBody() {
        }
        
        public EnlightenResponseBody(string EnlightenResult) {
            this.EnlightenResult = EnlightenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface calaisSoapChannel : OpenCalais.Calais.calaisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnlightenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EnlightenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public OpenCalais.Calais.EnlightenResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((OpenCalais.Calais.EnlightenResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class calaisSoapClient : System.ServiceModel.ClientBase<OpenCalais.Calais.calaisSoap>, OpenCalais.Calais.calaisSoap {
        
        private BeginOperationDelegate onBeginEnlightenDelegate;
        
        private EndOperationDelegate onEndEnlightenDelegate;
        
        private System.Threading.SendOrPostCallback onEnlightenCompletedDelegate;
        
        public calaisSoapClient() {
        }
        
        public calaisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public calaisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calaisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calaisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<EnlightenCompletedEventArgs> EnlightenCompleted;
        
        public OpenCalais.Calais.EnlightenResponse Enlighten(OpenCalais.Calais.EnlightenRequest request) {
            return base.Channel.Enlighten(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginEnlighten(OpenCalais.Calais.EnlightenRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEnlighten(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public OpenCalais.Calais.EnlightenResponse EndEnlighten(System.IAsyncResult result) {
            return base.Channel.EndEnlighten(result);
        }
        
        private System.IAsyncResult OnBeginEnlighten(object[] inValues, System.AsyncCallback callback, object asyncState) {
            OpenCalais.Calais.EnlightenRequest request = ((OpenCalais.Calais.EnlightenRequest)(inValues[0]));
            return this.BeginEnlighten(request, callback, asyncState);
        }
        
        private object[] OnEndEnlighten(System.IAsyncResult result) {
            OpenCalais.Calais.EnlightenResponse retVal = this.EndEnlighten(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEnlightenCompleted(object state) {
            if ((this.EnlightenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EnlightenCompleted(this, new EnlightenCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EnlightenAsync(OpenCalais.Calais.EnlightenRequest request) {
            this.EnlightenAsync(request, null);
        }
        
        public void EnlightenAsync(OpenCalais.Calais.EnlightenRequest request, object userState) {
            if ((this.onBeginEnlightenDelegate == null)) {
                this.onBeginEnlightenDelegate = new BeginOperationDelegate(this.OnBeginEnlighten);
            }
            if ((this.onEndEnlightenDelegate == null)) {
                this.onEndEnlightenDelegate = new EndOperationDelegate(this.OnEndEnlighten);
            }
            if ((this.onEnlightenCompletedDelegate == null)) {
                this.onEnlightenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEnlightenCompleted);
            }
            base.InvokeAsync(this.onBeginEnlightenDelegate, new object[] {
                        request}, this.onEndEnlightenDelegate, this.onEnlightenCompletedDelegate, userState);
        }
    }
}
