<?xml version="1.0" encoding="UTF-8"?>

<wsdl:definitions
  targetNamespace="http://citeseerx.org/algorithms/parscit/wsdl"
  xmlns:ens="http://citeseerx.org/algorithms/parscit/xsd/error-messages"
  xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:tns="http://citeseerx.org/algorithms/parscit/wsdl"
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <wsdl:message name="extractCitationsRequest">
    <wsdl:part name="unprocessedText" type="xsd:string" />
  </wsdl:message>

  <wsdl:message name="extractCitationsResponse">
    <wsdl:part name="citations" type="xsd:string" />
  </wsdl:message>

  <wsdl:message name="ParsCitFault">
    <wsdl:part name="message" type="xsd:string" />
  </wsdl:message>

  <wsdl:portType name="ParsCit">
    <wsdl:operation name="extractCitations">
      <wsdl:input message="tns:extractCitationsRequest" />
      <wsdl:output message="tns:extractCitationsResponse" />
      <wsdl:fault name="ParsCitFault"
                  message="tns:ParsCitFault" />
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="SOAPBinding" type="tns:ParsCit">
    <soap:binding style="rpc"
                  transport="http://schemas.xmlsoap.org/soap/http" />
      <wsdl:operation name="extractCitations">
        <soap:operation soapAction="" style="rpc" />
        <wsdl:input>
          <soap:body use="encoded"
                     namespace="urn:Parser"
                     encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
        </wsdl:input>
        <wsdl:output>
          <soap:body use="encoded" namespace="urn:Parser"
                     encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
        </wsdl:output>
      </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="ParsCitService">
    <wsdl:port name="ParsCit" binding="tns:SOAPBinding">
      <soap:address location="http://services.bibliopedia.org:80/ParsCitServer.cgi" />
    </wsdl:port>
  </wsdl:service>

  <plnk:partnerLinkType name="parsePartnerLT">
    <plnk:role name="Parser" portType="tns:ParsCitPT" />
  </plnk:partnerLinkType>

</wsdl:definitions>
